language:
 - python
python:
 - '2.7'
 - '3.7'
install:
 - pip install -r requirements.txt
 - pip install codecov
 - pip install pytest-cov
script:
 - python test_Login.py
# - pytest --cov=./  --cov-report=xml tests/
#after_success:
# - codecov --file coverage.xml --token $CODECOV_TOKEN


