language:
 - python
python:
 - '2.7'
 - '3.7'
install:
 - pip install codecov
script:
 - pytest --cov=./  --cov-report=xml tests/
after_success:
 - codecov --file coverage.xml --token $CODECOV_TOKEN


